### ISSUE TITLE
Integrate with Application's Menu?

### ISSUE THREAD

**Issue by anonimo1w** [lestcape/Gnome-Global-AppMenu#10]
In Gnome-Shell, by default, appear on the top bar "Activity - Application's Menu [...]". Is possible to integrate your extension with Application's menu so every menu from some apps can be reached in that way too (in case one want to have the same behaviour of Unity but with the Guidelines of Gnome-Shell)?

**Comment by lestcape** [comment]
Yes it's possible... But see, this will create a dependency of this extension, that will create probably  serius problems if the gnome extension will be removed. My idea it's place it at the right of this extension, but there are not space from the menu then, so, the icon and name of the application need to be hide probably, to used the gnome extension icon and name.

**Comment by Shtoomik** [comment]
I think he meant the default Gnome-Shell Application Menu, the one that shows the apps menu.

https://i.imgur.com/rPblHcX.png

**Comment by lestcape** [comment]
Thanks @Shtoomik 

Well, really the problem it's that: merge two extension that can be disable individuals will be a bad idea, like currently proved to be a bad idea replace the activities button. So, i think the best will be, add the extension in an individual way, but probably still the code of the Application Menu and hide then the real  or destroy it, but do not merged one code with the another to avoid conflicts...

Please see: https://github.com/lestcape/Gnome-Global-AppMenu/pull/14

**Comment by PHPJosh** [comment]
https://extensions.gnome.org/extension/591/remove-app-menu/ goes well with this global application menu

**Comment by lestcape** [comment]
Work in progress... Please report any problem... I can not test all possible combinations...

**Comment by lestcape** [comment]
https://github.com/lestcape/Gnome-Global-AppMenu/pull/39
