### ISSUE TITLE
Not rendering in top bar, but when I press alt, it seems to work okay

### ISSUE THREAD

**Issue by dessalines** [lestcape/Gnome-Global-AppMenu#18]
An screen of what happens when I press alt:

![image](https://cloud.githubusercontent.com/assets/930215/25257932/8ff56746-25f0-11e7-9e58-c10ff0bcef88.png)

**Comment by lestcape** [comment]
Please, see other related issues... You have an extension that hidden your activity button? Please remove it.

**Comment by dessalines** [comment]
Ah thanks that was it, the hide activities plugin conflicted with it.
