### ISSUE TITLE
Does not work with Ubuntu 17.04

### ISSUE THREAD

**Issue by mweisshaupt1988** [lestcape/Gnome-Global-AppMenu#2]
OS: Ubuntu 17.04
Gnome-Shell: 3.24.0
Extension version:  b601821
Unity is installed and working

The Extension can't be initialized because of this error:
Error: connect() takes two args, the signal name and the callback
TypeError: activities.actor.get_parent(...) is null

Thank you.
![gnome-global-appmenu-bug](https://cloud.githubusercontent.com/assets/3426126/25175497/48c28ef8-24fb-11e7-8e56-bba60b268834.jpg)

**Comment by lestcape** [comment]
Same reason of https://github.com/lestcape/Gnome-Global-AppMenu/issues/6
