### ISSUE TITLE
Hide application title when window maximized

### ISSUE THREAD

**Issue by imanhodjaev** [lestcape/Gnome-Global-AppMenu#22]
At the moment when window is maximized application title is also shown. Is it possible to hide it?

**Comment by lestcape** [comment]
It's possible if you modify the properties of the specific windows outside the shell. There are extensions for gnome shell that make this tasks. But there are not a way inside the shell to make it as an optional feature or something. This type of things could be a Mutter relate feature and it's the best way to do that and it's easy to do that, but apparently, this is not interesting for Gnome shell developers.

I will not want to add an external procedure that could be slower and buggy in several cases. So, you will need that https://extensions.gnome.org/extension/354/maximus/

**Comment by lestcape** [comment]
Probably be more up to date: https://extensions.gnome.org/extension/723/pixel-saver/

**Comment by imanhodjaev** [comment]
@lestcape Thank you!
