### ISSUE TITLE
Global Menu Positioning

### ISSUE THREAD

**Issue by TuffHub** [lestcape/Gnome-Global-AppMenu#23]
It'ld be nice to be able to set the position on the top panel manually, as it is now left of the "Places" extension. Any way to do it by myself?

**Comment by lestcape** [comment]
This need to be a feature of the desktop it self, like it's in cinnamon a feature. I try to port the cinnamon panels as a replace of the gnome shell panel, allowing this options, but it's difficult and it's not related with any specific extension. So, you can try to report this as a gnome shell issue.

**Comment by lestcape** [comment]
For a reference of my intentions: https://github.com/lestcape/Classic-Gnome
