### ISSUE TITLE
How to add padding on each menu?

### ISSUE THREAD

**Issue by agungshiro** [lestcape/Gnome-Global-AppMenu#24]
I thing the menu are too closer each other and need more space, how should I do to modify them ,
Thank you

**Comment by lestcape** [comment]
Ohhh thats really a problem, because i think there are not space... Mmm there are a way of course this can be decide in the gnome shell theme.

**Comment by neowiz73** [comment]
you might have to add some code to your gnome-shell.css.  be sure to search for this before adding it, i've discovered in some themes this already existed but needed to be adjusted. change the spacing to desired amount. 

`.applet-menu-content {
     spacing: 0.5em;
}`
