### ISSUE TITLE
Menu are still showed after close or show the desktop

### ISSUE THREAD

**Issue by agungshiro** [lestcape/Gnome-Global-AppMenu#25]
Menu are still showed after close or show the desktop

**Comment by lestcape** [comment]
@agungshiro yes, other gnome shell extension are still showed... If you think this is designed to be identically of the appmenu of gnome shell you are wrong, is not. I don't see any reason of why hide it, just the opposite... Do you see a reason?

**Comment by xpduyson** [comment]
1. Open Google Chrome, AppMenu show in topbar
2. Switch to next workspace without Chrome, the menubar still in topbar

short video explains the situation: https://zippy.gfycat.com/CostlyUnconsciousBuzzard.webm

**Comment by rmoravcik** [comment]
I have a the same problem using the Firefox on my Ubuntu 17.04.

**Comment by lestcape** [comment]
Mmm, i think the case of @xpduyson could be a reason, it's probably an unwanted thing... I will see what can i do with it.

**Comment by GNOME-IS-LIFE** [comment]
i +1 this. It's a pretty annoying bug...

**Comment by lestcape** [comment]
I merge the global menu with the appmenu, there are more things to do, but now the global menu is working more less than the gnome shell appmenu... Please open another issue if this error persist for some cases, but the general problem is fixed.
