### ISSUE TITLE
Plugin doesn't appear

### ISSUE THREAD

**Issue by anabolikas** [lestcape/Gnome-Global-AppMenu#31]
Hello,
I use gnome3 on linux mint 18.1 and I've just followed all the steps provided from how-to, enabled the plugin in gnome tweak tool, but it simply doesn't appear in my panel. How could I troubleshoot the problem?

**Comment by anabolikas** [comment]
Solved after adding "GTK_MODULES=globalmenu-gnome" to .bashrc.

**Comment by lestcape** [comment]
Probably you have a cinnamon session and you active the experimental behaviour of the global menu in the cinnamon session... When you swap to gnome, your settings can not be set from the extension to active the global menu as it's set in your root files, then you need to manually enabled it...

But it's just what I think happens, I'm not sure.

**Comment by anabolikas** [comment]
Thank you for the answer. I don't have cinnamon and I've never even tried it.

**Comment by anabolikas** [comment]
Heh, sorry, wrong info. It appeared after I removed a menu plugin. So I have found out that I'm not able to have any plugin before yours to keep it working. Tested with 2 menu plugins positioned in top left corner - both disables global menu.

**Comment by lestcape** [comment]
Yes, read other issues. This menu use the activity button an is incompatible at the moment with any other than use the same button, of course.

**Comment by lestcape** [comment]
This not occurs now, i think...
