### ISSUE TITLE
Menu Item Visibility Issue While using with light colored shell theme

### ISSUE THREAD

**Issue by flourishdna** [lestcape/Gnome-Global-AppMenu#32]
The menu items are not visible while using it with light colored shell theme. There should be an option to enable dark text. I have included the screenshot below.

![selection_004](https://cloud.githubusercontent.com/assets/8165585/26445145/b07c2072-415c-11e7-96d1-4b19b0896356.png)

**Comment by lestcape** [comment]
This is not the way. The themes need to be make base on components not the opposite. The change is required inside the theme and not inside the global menu.
