### ISSUE TITLE
Multiple Application Name and Icon while using with Gnome Tweak Tool

### ISSUE THREAD

**Issue by flourishdna** [lestcape/Gnome-Global-AppMenu#33]
Two application names and icons are shown for the same application. I have tried disabling the Gnome Tweak Tool top application menu option from **Top Bar** >> **Show Application Menu**, but it keeps getting enabled automatically. This happens only when Gnome Global AppMenu is installed and active. I have reinstalled the OS 3 times and the issue still exists. I have included a screenshot below.

The issue exists in Ubuntu 16.04.2 and 17.04 (Gnome).

## Screenshot of the issue:
![image](https://cloud.githubusercontent.com/assets/8165585/26529850/effdc1de-43e5-11e7-94e0-e717ebee4c32.png)

## Screenshot of the Application Menu in Gnome Tweak Tool:
![image](https://cloud.githubusercontent.com/assets/8165585/26529909/499fa864-43e7-11e7-996f-c867b1cd9a81.png)

**Comment by lestcape** [comment]
Yes, the global menu enable this feature by default and not observed the settings. I'm working on migrate all appmenu code to work inside the global menu. I don't know if i can support this options in the future.

This have a low priority to me for now.

**Comment by lestcape** [comment]
Fixed.

**Comment by flourishdna** [comment]
@lestcape wow, that was quick. Thank you.

**Comment by lestcape** [comment]
@flourishdna you can now enable the appmenu and in the setting of the extension you can set the extension to be used as a replace of the appmenu. In that way you will have both types of menus working together like in unity desktop, but without the side effect of duplicate the icon and the application name.
