### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by Meiden-fc** [lestcape/Gnome-Global-AppMenu#34]
Hi there. I don't really know what is the problem, but the extension isn't working at all.

I mean, it doesn't show the menu either in the active window nor in the topbar (as it should).

My gnome-shell version is GNOME Shell 3.18.5 on Ubuntu 16.04.2.

---------------------
Hola. No sé realmente cual es el problema, pero la extensión no funciona en absoluto.

Me refiero: no muestra ningún menú ni en la ventana activa ni en la barra superior (como debiera)

Estoy utilizando GNOME Shell 3.18.5 en Ubuntu 16.04.2.

Muchas gracias.

**Comment by lestcape** [comment]
Realmente nunca la he probado para GNOME Shell 3.18. Te aconsejo que subas de version, no creo que pueda probarla en 3.18.

**Comment by Meiden-fc** [comment]
Actualizado a GNOME Shell 3.20.4 y sigue sin funcionar. Imagino que será necesario 3.22 o superior. Una lástima. Gracias por tu ayuda Lester.

**Comment by lestcape** [comment]
No, si debe de funcionar. La computadora donde estoy ahora:
gnome-shell --version
GNOME Shell 3.20.4

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

Quien sabe que hiciste. Tu lo instalaste usando gnome twek tools o solo lo copiaste a la carpeta como en cinnamon y piensas que eso es instalarlo en gnome shell?

**Comment by Meiden-fc** [comment]
Pues algo había hecho mal, porque ahora funciona. Sí que lo había activado en tweak tools, pero no sé qué pudo pasar. Ahora descargué el zip de nuevo, lo descomprimí, lo activé en tweak tools y al reciniciar funcionaba como debe.

Muchas gracias Lester. Me he pasado de Cinnamon a GShell para poder seguir disfrutando de tu globalmenu.
