### ISSUE TITLE
Request for dual screen support

### ISSUE THREAD

**Issue by davidgxxl** [lestcape/Gnome-Global-AppMenu#35]
Hi lestcape.

This isn't an issue but a functionality request.

I'm trying this useful extension on Archlinux with gnome 3.24 and works very well.

Most of time I work with dual screen desktop configuration and I'll be happy and grateful to see the dual screen support in this extension if possible.

Cheers!

**Comment by lestcape** [comment]
Yes, but i have one monitor, and i need to do that with two monitors, so the option is in a virtual box create two monitors and then see what I'm doing. the problem it's as i know gnome shell only have one panel. So, tell me where will come the extension in a monitor without panels?

**Comment by davidgxxl** [comment]
Oh I see.

Well I added an aditional panel on my second screen using the multi monitors add-on extension. So I think this request is out of scope in the development on your extension. 

Please feel free to close this issue.

Thanks.

**Comment by lestcape** [comment]
No, i will not close it for now. In fact i will want to do that, just i think a third-partly extension is not the properly authority to handled the desktop. Is gnome shell who need to defined the desktop protocols. So all extensions will have a uniform way to detect panels and then will can decided and set things in a right way... Follow specific third-partly extensions, is create the chaos.

**Comment by davidgxxl** [comment]
You right.

Well i can help testing in the future if become posible develop this functionality.

Thanks and Regards.

**Comment by skad** [comment]
I'm very interested to :D

**Comment by PHPJosh** [comment]
well if you still doing this the dash to dock extension add Monitor isolation to it so  apparently for multi monitor support and I guess each dock is different on each monitor? if I was you I would look at their code as it could be useful for you in this.  https://github.com/micheleg/dash-to-dock

**Comment by lestcape** [comment]
@PHPJosh I'm not doing this and i do not do it for another different project to my own project or the gnome shell API. This means:

1- I will create a gnome shell multi-panel extension and make support to my own extensions.
2- I will used the gnome shell api if in some day, the Gnome Shell decide implement it.

There are not more option to me. Depend of external things, is in my opinion create the chaos and i will not do that.

**Comment by DEvil0000** [comment]
I'm also very interested. I have 3 monitors with my ubuntu 18.04 laptop here using the same extensions as you guys. As soon as there is something I can test let me know ;)

**Comment by lestcape** [comment]
@DEvil0000 well sorry, will not be implemented. Try to request support for the shell itself and i will try to do something, but without a default possibility to set several panels from the shell I will never implement it.

**Comment by lestcape** [comment]
This error was migrated to gitlab, as the development of this extension, will no longer be in github from the recently acquisition from the Microsoft company of the github website. Please to continued following it you can subscribed in this thread:
https://gitlab.com/lestcape/Gnome-Global-AppMenu/issues/35
