### ISSUE TITLE
AppMenu conflicts with Hide activities button extension

### ISSUE THREAD

**Issue by xbonio** [lestcape/Gnome-Global-AppMenu#41]
Having Gnome-Global-AppMenu and Hide activities button extensions enabled results in some sort of conflict: every time I log in, the Activities button is shown on the left of Gnome-Global-AppMenu.

```
$ lsb_release -a
     
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
```
```
$ gnome-shell --version
GNOME Shell 3.24.2
```
```
$ cat .git/refs/heads/master                                        
14afab20255ebc95420ee3170790fd75f2a38ab2
```

**Steps**:
1. Enable Gnome-Global-AppMenu extension
2. Enable Hide activities button extension (https://extensions.gnome.org/extension/744/hide-activities-button/)
3. Make sure Gnome-Global-AppMenu is visible and Activities button is **not** visible
4. Log out, log in

**Expected result**:
Gnome-Global-AppMenu is visible and Activities button is **not** visible.

**Actual Result**:
Both Gnome-Global-AppMenu and Activities button are visible.

**Comment by lestcape** [comment]
Yes, i don't test it yet, but the position of global menu is estimate with base on the activity button... Probably hide-activities-button could cause a wrong behaviour for the global menu. I will need to take this more carefully and not depend of things if they are not available. Give me a chance... When i have the time i will see what can i do.

**Comment by lestcape** [comment]
I can not reproduced the issue... You sure have another problem.
Hide Activities Button only do what is say:
```
indicator.container.hide();

**Comment by xbonio** [comment]
I disabled all other extensions and the problem still exists.

**Comment by lestcape** [comment]
I can not tell you to much, because the bugs occurs with a logout... Can you you detected if also occurs with a gnome shell restart??? I can obtain useful information if all will occurs without close the session, but if not... I can not detected from where the bug come or what really happen... I believe in you, just i have not idea how can be possible this...

**Comment by lestcape** [comment]
@xbonio i can reproduced this behaviour in another computer... I will try to fixed it.

**Comment by xbonio** [comment]
Reproduces either with gnome shell restart and with just re-enabling Gnome-Global-AppMenu extension.

**Comment by xbonio** [comment]
You fixed this, works for me.
