### ISSUE TITLE
Changeable position!

### ISSUE THREAD

**Issue by bresilla** [lestcape/Gnome-Global-AppMenu#42]
Would be cool if i can change the position, of GlobalMenu. Would be really nice if it could be in the middle, or in the right!

![screenshot-20170711155232-3839x113](https://user-images.githubusercontent.com/10802141/28071747-21676ae4-6651-11e7-97bf-396c3e8c7005.png)

**Comment by lestcape** [comment]
Do you think this feature will be nice for the global menu? I think will be nice if users could set all actors inside the panel in the position they will want. Set the global menu in some specific position without take in account the panel configuration, will not be nice for me...  Actually will be a miss. To be possible create an option like that, all actors inside the panel will need to allow the same. This is the only way for me. So, what you request is for me a request for gnome shell itself not for specific extensions... I will not want to create chaos in the panel and a lot of conflicts with other extensions, so i will not implement this here.

Instead, I'm trying to create an extension to handled a behaviour like this (https://github.com/lestcape/Classic-Gnome). It's a replace of the gnome shell panels with the cinnamon panels (they have support for this).  But it will never be the best way, as I say this is a request for gnome shell and not for an extension, but could help to organize a litle the missing protocols of gnome shell ... Of course, will not work for all extensions, as other extensions don't need to follow any rule this new extension.

**Comment by HEXcube** [comment]
Would it be possible to set the Global Menu to appear just after GNOME AppMenu? See images:

**Current Position**:

![Global Menu - Current](https://user-images.githubusercontent.com/3755396/28246922-b238aa4c-6a43-11e7-8621-63178160aefd.png)

----

**Proposed Position**:

![Global Menu  - Proposed](https://user-images.githubusercontent.com/3755396/28246928-e9df85b0-6a43-11e7-8716-0efadd8193b7.png)

If set like that, I could just disable the redundant app icon and name from Global Menu settings and get some more space for the menu. :relaxed:

**Comment by lestcape** [comment]
You have an option to disable/enable the gnome appmenu, please see: https://github.com/lestcape/Gnome-Global-AppMenu/issues/45

And see:
https://user-images.githubusercontent.com/1389572/28146563-8d50d5f2-6740-11e7-8715-b1a64007bcf0.png

**Comment by HEXcube** [comment]
> You have an option to disable/enable the gnome appmenu, please see: #45

@lestcape  Yeah, but that option removes the GNOME AppMenu! :worried: What I meant in my previous comment was to keep GNOME AppMenu and then show the Global Menu after it.

Are there any technical limitations in doing that? Or is the position of GNOME AppMenu non-changeable as implemented by GNOME Shell? :confused:

**Comment by lestcape** [comment]
Yes and not. The gnome shell actor will be set after all third-party actors in the panel and they are hard set. I can not satisfy all configuration that you want to have. I designing it to remove the gnome appmenu, not to have it... What will be the reason of let it? is duplicate, as gnome appmenu is also included in the global menu.

**Comment by HEXcube** [comment]
> What will be the reason of let it? is duplicate, as gnome appmenu is also included in the global menu.

@lestcape  If AppMenu's available in Global Menu, then no problem, I'd disable it. All this time I thought those menu entries will be lost if I disable AppMenu. And now that #43 is fixed, I'd just enable to merge menus and show just the app icon. :relaxed:

**Comment by lestcape** [comment]
Well, i create the same mechanism of the gnome appmenu inside the global menu... There are a difference, for example for firefox gnome appmenu show a dummy menu with only an option to close it... When this happen i do not include the dummy appmenu (because is for nothing is only annoying). When the appmenu have a real menu, i merged it with the global menu... This is exactly how this occurs in unity desktop.

**Comment by lestcape** [comment]
See the terminal for example, this menu is the gnome appmenu working embedded inside the global menu:

![captura de pantalla de 2017-07-16 14-02-17](https://user-images.githubusercontent.com/1389572/28250489-9b3b0452-6a2f-11e7-92c1-4918e223cd1b.png)

**Comment by HEXcube** [comment]
> There are a difference, for example for firefox gnome appmenu show a dummy menu with only an option to close it... When this happen i do not include the dummy appmenu (because is for nothing is only annoying)

That's a good choice. :+1: Would've been pretty pointless to have just a 'Quit' in menu. I often wondered why AppMenus do that.


> When the appmenu have a real menu, i merged it with the global menu... This is exactly how this occurs in unity desktop.

Didn't know Unity did it too! I thought Unity 7 just dropped the AppMenu altogether and used patched-in classic menus for all the GNOME Apps.

**Comment by HEXcube** [comment]
I enabled the _"Use the extension as a replacement of GNOME AppMenu"_ option as u advised, and it's perfect now! :relaxed: Combined with the option to hide app name, now I have plenty of space for the menu.

![Chrome - Global Menu](https://user-images.githubusercontent.com/3755396/28280286-e0f869b4-6b40-11e7-9d44-a2460f7719fc.png)

Well, almost... :sweat_smile: 

![LibreOffice - Global Menu](https://user-images.githubusercontent.com/3755396/28280150-6be159ec-6b40-11e7-8133-c2d6c1f2a466.png)

**Comment by lestcape** [comment]
Well, this will not be implemented here. Need to be a request for the gnome shell itself. So, closing it...
