### ISSUE TITLE
App icon not shown if 'show app name' is disabled

### ISSUE THREAD

**Issue by pablitok** [lestcape/Gnome-Global-AppMenu#43]
If I want to see the app icon, i have to enable the 'show app icon in panel' option and the 'show app name' or the icon is not shown. If I want to see  the app name but not the icon, it works fine

**Comment by lestcape** [comment]
I can reproduced it...

**Comment by pablitok** [comment]
You can't? Any way I can help you? a list of plugins? gnome shell 
version? some log?

**Comment by lestcape** [comment]
I don't need help here, but thanks. Like i say, i can reproduced it very easy... I will fix it...
