### ISSUE TITLE
gnomeGlobalAppMenu@lestcape/utils/environment.js” failed:: Command not found

### ISSUE THREAD

**Issue by pablitok** [lestcape/Gnome-Global-AppMenu#44]
When I turn on the set static env menu proxy variable option, I get this error. The file exists

**Comment by pablitok** [comment]
Nevermind: `sudo apt install cjs` is the solution

**Comment by lestcape** [comment]
Not, mmmm This is a problem... I need to swap the header files to gjs instead of cjs. Thanks.
