### ISSUE TITLE
Global menu and appmenu window title

### ISSUE THREAD

**Issue by pablitok** [lestcape/Gnome-Global-AppMenu#45]
I'm using Gnome Global Appmenu and i wish to see the focused window title, but when I enable the Global Menu, the appmenu window title extension stops working.

**Comment by lestcape** [comment]
I don't understand your point... If you see the settings you can used this implementation of the global menu as a replace of the gnome appmenu implementation or not. If you used it as a replace, you will not see the appmenu, but if you used it without replace the gnome appmenu, you don't see the gnome appmenu.

This implementation merged inside both types of menus, the traditional menus and the appmenu (the same menus of gnome), So, i think is ok, that you don't want to used the gnome implementation then... 


What is the problem?

**Comment by pablitok** [comment]
This is how I see my top bar with GlobalMenu disabled
![captura de pantalla de 2017-07-12 22-13-18](https://user-images.githubusercontent.com/6256423/28146332-6e76b750-674f-11e7-9efc-2429a76b6a0d.png)

When I enable GlobalMenu, I lost the window title. I can see it if I enable it in your extension, but I'd prefer using another extension because:
1) I like having the window title after your extension
2) Your extension only allows 60 characters of title at most
3) If the window title changes, it doesn't change in your extension but it does in others

**Comment by lestcape** [comment]
![captura de pantalla de 2017-07-12 20-25-47](https://user-images.githubusercontent.com/1389572/28146563-8d50d5f2-6740-11e7-8715-b1a64007bcf0.png)

**Comment by lestcape** [comment]
Set this option to off resolve your problem?

**Comment by pablitok** [comment]
Great! mil gracias! sos un genio!

**Comment by lestcape** [comment]
Esa es la razón por la cual te marque esto como invalido... Yo creo que la mayoría de las personas, no van a querer ver dos iconos en el escritorio, por eso por defecto está puesta en on...

**Comment by pablitok** [comment]
El mié, 12 de jul 2017 a las 10:34 , Lester Carballo Pérez 
<notifications@github.com> escribió:
> Esa es la razón por la cual te marque esto como invalido... Yo creo 
> que la mayoría de las personas, no van a querer ver dos iconos en el 
> escritorio, por eso por defecto está puesta en on...

La idea no es ver dos veces el icono, si no poder usar por ejemplo 
PROMPT_COMMAND para modificar el titulo de la ventana de gnome-terminal 
(con el valor de `pwd` por ejemplo), o ver en la top bar el titulo de 
la ventana de sublime_text

**Comment by lestcape** [comment]
Por supuesto que si.... Estoy de acuerdo... ¿Pero a cuantos les importa mucho eso? La verdad es que si hubieses solicitado que todas esas opciones fueran a parar al menú global, te estuviese entendiendo perfectamente. ¿Qué es lo que quieres entonces? ¿Ver todas esas opciones en el menú global? Específicamente la de usar el título de la ventana en lugar del título de la aplicación... Eso es fácil de lograr...  Y ese el el problema de porqué no cambia... Tambien puedo poner una opción para cambiar el texto a un texto normal, como el de gnome shell. Tampoco es difícil y tambien puedo hacer que -1 signifique no limitar el texto, pero todo eso tiene contras y eso es lo que me preocupa...

**Comment by pablitok** [comment]
No te quiero molestar con un "wishlist" de opciones que se adecuen a 
mis gustos especificos, ya me voy a sentar a leer un poco asi aprendo a 
crear extensiones a ver si puedo hacer algun aporte, gracias!
