### ISSUE TITLE
Application name truncated

### ISSUE THREAD

**Issue by xbonio** [lestcape/Gnome-Global-AppMenu#46]
Every single application has it's name truncated in the extension. No matter whether it's short (like Atom, Opera, Files) or long (like Shell Extensions or Sublime Text) - it's always truncated at ~80%.

```
$ lsb_release -a
     
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
```
```
$ gnome-shell --version
GNOME Shell 3.24.2
```
```
$ cat .git/refs/heads/master
55da841bc3ddd12f8e556e9387b4d0329bf8e00a

```
![screenshot from 2017-07-13 10-48-34](https://user-images.githubusercontent.com/14818302/28158214-4d7ae822-67b9-11e7-8333-6a75bec9da7b.png)
![screenshot from 2017-07-13 10-49-16](https://user-images.githubusercontent.com/14818302/28158220-516d3dea-67b9-11e7-99aa-ad9df1b3057c.png)

**Comment by lestcape** [comment]
Yes this is an intentional behaviour, but i know that is not a nice behaviour... The problem is a big name will expand the menu too much... So, we need to set set a limit some how and for another hands the text is not a real text is a "picture" of the real text with a gradient... This is to set a separation between the application name and the menu... Is easy to click outside the menu, so this help a little the user... 

If you have a good idea of how resolve that problems please tell me...

**Comment by xbonio** [comment]
I'd like it to look similar to OSX's app menu but I know it might not be possible to imitate it 1:1.
![screenshot from 2017-07-13 11-35-19](https://user-images.githubusercontent.com/14818302/28160076-610feec2-67bf-11e7-8b9c-e69b46e5ccf6.png)

Maybe try to display the full name of application and if there's no space to display the full menu, let users limit the extension length by setting maximum size of the application name?

**Comment by lestcape** [comment]
That's a little hard to know. Some text can be ellipse and that is what i don't want to happen, so you can think there are space when really there are not and text are ellipse, because of this. I prefer to have an effect than use the third points "...". This is what happen when a text is ellipse in gnome shell (clutter), the third points appear.

**Comment by lestcape** [comment]
For another hands, Mac Os is thinking to follow a design that included the global menu. So, there are a big area where the menu is supposed to will be displayed... Here is not in that way, there are not space by default in the panel and create the necessary space is equivalent to install several extensions...

**Comment by xbonio** [comment]
I think that if there is space on the panel for the full app name to be shown, it should be displayed. If not, it should be truncated and ellipsis should be appended.

**Comment by elsieholmes** [comment]
I think that there should be an option in the extension settings which would let the end user decide if he/she wants it to look default or macOS way.

**Comment by corebots** [comment]
imho there is no rason to 'shorten' the app name on bigger screens, for example on my 27" screen there always is enough space left on the left side of the panel ( i mean left to the clock, where the menu appears. 

PS the way macOS handles it is actually a well thought-of concept, not just menu displaying... it would be nice to see some better implementation but to have it working at least as good as in macOS (with all corner cases and possibilities handled properly) is hard enough already imho, if you could push the functionality further, without compromises, i think everybody would welcome that; but but the macOS way is a pretty decent reference design already.

**Comment by lestcape** [comment]
I agree with @elsieholmes so, I will try to add an option to swap to a different implementation where i will not limited anything, but this could not be the default one. I really disagree with other comments. I don't try to imitate MacOS or something... In fact i can not do that, I never had a MacOS in my life. I think this will not look nice, but well... 

Just you are thinking only on the global Menu components...  I say **all actors** in the panel will be ellipsis if there are not space in the panel... That will look like catastrophic, anyway.

**Comment by lestcape** [comment]
You can set the Maximum size of the application name to 0 if you don't want cut the text, also if you don't want a degradation a normal St.Label will replace the drawingArea and then the text will not be render with a gradient, instead will be a normal St.Label. You also have a way to control the wrap mode of the applications name inside the panel and do not let clutter to wrap the text and ellipsize it. This is set in the option Wrap the menu labels.

I hope now this will satisfy the request, of course i can not do anything more, i can not control in general how clutter will want to wrap things. This is an internal implementation of clutter...
