### ISSUE TITLE
Unnecessary hamburger menu in Options/Configuration

### ISSUE THREAD

**Issue by HEXcube** [lestcape/Gnome-Global-AppMenu#48]
The hamburger menu on top-right side of Options/Configurations window seems to have no purpose. On clicking, an empty dropdown's displayed. See:

![hamburger menu](https://user-images.githubusercontent.com/3755396/28247064-e36c2438-6a46-11e7-8396-58a060a79f60.png)
![hamburger menu - empty](https://user-images.githubusercontent.com/3755396/28247063-e36b9388-6a46-11e7-934b-40ea728572ba.png)
![hamburger menu - tootip](https://user-images.githubusercontent.com/3755396/28247062-e36b4720-6a46-11e7-95e0-b3a1f0c5b804.png)

**Comment by lestcape** [comment]
Yes... I need to hide it..

**Comment by lestcape** [comment]
https://github.com/lestcape/Gnome-Global-AppMenu/commit/c03e96566d74a460a4905659e8ea2ff67a91f955
