### ISSUE TITLE
Hide menubar from application

### ISSUE THREAD

**Issue by Lesik** [lestcape/Gnome-Global-AppMenu#49]
Hey,

great work on this extension! I love app menus. I will try my best to help.

I have encountered a bug. For example with Thunar (gtk2), the appmenu shows up in the panel, but it is not hidden from the application itself, resulting in a double menubar:

![bildschirmfoto von 2017-07-19 13-33-39](https://user-images.githubusercontent.com/2021487/28364976-fb127b5e-6c86-11e7-89f5-c56bbd9c38e4.png)

The extension is fresh from git (c03e965), GNOME 3.22 (Wayland), Fedora 26.

**Comment by rilian-la-te** [comment]
Use appmenu-gtk-module from me. Unity-gtk-module from ubuntu relies on modified GTK2 by default.

**Comment by lestcape** [comment]
@Lesik  please see: https://bugzilla.redhat.com/show_bug.cgi?id=1387884
