### ISSUE TITLE
Not Working With Atom Editor

### ISSUE THREAD

**Issue by kholisrag** [lestcape/Gnome-Global-AppMenu#52]
The Ext is not working with atom , I'm not sure it's because atom or this ext...
The Menu is gone...
![screenshot from 2017-07-23 23-37-48](https://user-images.githubusercontent.com/4683704/28501140-f7025e7c-6fff-11e7-8660-e03838f2b8fa.png)

Or I suggest to add feature that exclude some/custom app

**Comment by lestcape** [comment]
You can used the unity features, this will work in gnome also, just try: http://www.webupd8.org/2011/03/disable-appmenu-global-menu-in-ubuntu.html

**Comment by lestcape** [comment]
Probably duplicate of this: https://github.com/lestcape/Gnome-Global-AppMenu/issues/40 also please see: https://github.com/atom/atom/issues/13885

**Comment by kholisrag** [comment]
not working with: http://www.webupd8.org/2011/03/disable-appmenu-global-menu-in-ubuntu.html
I solved with spotlight menu in atom shift+ctrl+p
Thanks,
Regards
Kholis

**Comment by lestcape** [comment]
If the experimental option to statically set the environment variable is enable this will not work, but i think it will work otherwise (you need a restart)... Regards.
