### ISSUE TITLE
Missing Global Menu

### ISSUE THREAD

**Issue by sulthonzh** [lestcape/Gnome-Global-AppMenu#53]
hi, i have problem, global menu missing when open project at `Visual Studio Code`, any solution for this bug?

**Comment by amid11** [comment]
1. Is it just vscode, have you tried to run it with ```sudo```? 

2. Do you have any other active gnome-extensions? have you tried disabling them? (in case of any confliction)

Using **gnome-tweak-tool** go to `gnome global application menu` under `Main menu` section activate `Automatically activate the main menu` option, then do ``` alt + f2``` input ```r``` and hit ```Enter```, then open vscode again see if It's working this time.

**Comment by Richie-8DK** [comment]
I just tested it. It worked fine, but after some time it disappeared. Your instruction made it work again.

**Comment by amid11** [comment]
@Richie-8DK I edited my reply, It stopped working for me too...

**Comment by lestcape** [comment]
Yes, this is probably the same of https://github.com/lestcape/Gnome-Global-AppMenu/issues/40

**Comment by sulthonzh** [comment]
working with restarting ('Alt + F2' input 'r' and hit 'Enter'), but same problem when open other project, but nice.

**Comment by lestcape** [comment]
@sulthonzh wait... When you open a new project the global menu is not displayed always? If that the case, the problem apparently is not the same of #40.

**Comment by sulthonzh** [comment]
@lestcape  yes right. and also after restart must focus on vscode window to show global menu again.

**Comment by lestcape** [comment]
@sulthonzh yes, after restart you must focus some window or what is supposed that it will show? So, i think  that part is in my opinion ok... I will need to install the VS, because if is not a problem of a wrong xwindows that the VS send, this probably can be easy fixed.

**Comment by lestcape** [comment]
Can anyone confirmed that the problem gone?

**Comment by sulthonzh** [comment]
@lestcape yeach,, awesome, but any problem with chrome when open together with vscode, may be only with me,

**Comment by lestcape** [comment]
@sulthonzh if you have a way to reproduced it, please open this problem in a new thread, that’s will be different, but if you can reproduced it i can try the same and see.
