### ISSUE TITLE
Query : Is it same as Gnome Global Application Menu in gnome extensions

### ISSUE THREAD

**Issue by niyasc** [lestcape/Gnome-Global-AppMenu#58]
I just came across [Gnome Global Application Menu](https://extensions.gnome.org/extension/1250/gnome-global-application-menu/) in gnome extension. Is it same as this one? If it is same, it would be better if README is updated to make it clear.

**Comment by lestcape** [comment]
@niyasc You can create a pull request to update the readme here to what you think it will be nice. But see, I'm not who upload it to the gnome extensions website, so i can not change it in gnome, please see: https://github.com/lestcape/Gnome-Global-AppMenu/issues/26
