### ISSUE TITLE
Conflicts with Application Menu

### ISSUE THREAD

**Issue by hanjiexi** [lestcape/Gnome-Global-AppMenu#6]
Hello,

I'm not sure if this is a problem with this extension or with the [Applications Menu](https://extensions.gnome.org/extension/6/applications-menu/) extension (or a limitation of Gnome Shell itself), but when both Applications Menu and Gnome Global AppMenu are enabled, this extension doesn't work; Applications Menu completely overrides it.

OS: Ubuntu GNOME 17.04
Gnome Global AppMenu extension version: [`b601821`](https://github.com/lestcape/Gnome-Global-AppMenu/commit/b601821fe5c6833c69e9742b0f3b9f84e89d93b6)

**Comment by lestcape** [comment]
Because both works as a replace of the activity buttons, the last that load gain the place.

**Comment by anonimo1w** [comment]
I have some extensions, Freon and OpenWeather, which can be at the right

**Comment by anonimo1w** [comment]
I have some extensions, like Freon and OpenWeather, which can be on the same side of AppMenu. This kind of behaviour would help in this issue? 
Or, is it possible to be on the same slot of AppMenu/Activity but moving it to the side?

**Comment by lestcape** [comment]
1- I don't think, the problem here is the space...
2- Yes, is possible, same problem, the size.

**Comment by lestcape** [comment]
Not anymore...
