### ISSUE TITLE
forked by Clement

### ISSUE THREAD

**Issue by kalinchernev** [lestcape/Gnome-Global-AppMenu#60]
I am interested into having the applet in cinnamon, but the other repo seems abandoned and marked as `forked by Clement` as an omen. Can you at least share a link to this fork?
Thanks!

**Comment by lestcape** [comment]
Explanation are inside this link: https://github.com/lestcape/Global-AppMenu/issues/50 
Please, use the another repo if you want more information ( I'm the same person, so...). The another repo is open, just because if some one like you want to forked it.
