### ISSUE TITLE
Empty menus 

### ISSUE THREAD

**Issue by pablitok** [lestcape/Gnome-Global-AppMenu#61]
When I use the slack app with this extension, the menu is shown in the bar, but when I click in any option (File, edit, etc) the content of the menu dropdown is displayed for less than a second and then the dropdown gets empty (only a thin bar is shown), when I do alt+tab to other windows and get back to slack, there's  a little "flash" or something (like a redraw) and again if I click in any option the content of the dropdown is displayed for less than a second, the dropdown closes and when I try to open it, is empty again

**Comment by lestcape** [comment]
You know if is working on unity?
Can you give me a link to the slack app?

I think the app don't remember the menu elements ids and the global menu implementation refresh the visible id's constantly, this probably is the cause of the problem. the solution could be do not update the visible elements just one time, but it will create problem with application that change his menus on fly,

**Comment by pablitok** [comment]
I don't have unity to test, but I'm 99% sure that it's working.
You can get it here https://slack.com/downloads/linux

**Comment by lestcape** [comment]
Yes is an electron app. The electron apps won't work nice with this implementation: https://github.com/electron/electron/issues/8455

As we are in js, spawning the session is critical.

**Comment by pablitok** [comment]
Oh, ok,
Is there a way to blacklist the app?

**Comment by lestcape** [comment]
Is supposed that you can set in your environment: ELECTRON_FORCE_WINDOW_MENU_BAR=1 (disables globalmenu integration) for electron applications. Read this in the link i shared with you.

Also you can used this method, but you will need to disable (if you enabled it) the experimental option to hard-code the environment variables in the global menu settings or will not work.
http://www.webupd8.org/2011/03/disable-appmenu-global-menu-in-ubuntu.html

**Comment by pablitok** [comment]
The option that you talk about is the first one? in spanish it says 
'establecer estaticamente la variable de entorno'
I have it disabled, but if I use the ELECTRON_FORCE_WINDOW_MENU_BAR=1 
env variable, I end up with  no menu bar anywhere

**Comment by lestcape** [comment]
It suppose that this is specific for electron app only: https://github.com/electron/electron/issues/8455#issuecomment-315380862

**Comment by lestcape** [comment]
Si, la opción es esa. Habilitarla significa desabilitar el menu global para las aplicaciones que corren como root. El menu global funciona a nivel de sessión, por lo que las aplicaciones a nivel de root exportan el menu hacia la sessión de root, donde no está corriendo el soporte para capturar el menu, por lo que estas aplicaciones pierden su barra, pero el menu global no se muestra. Ejemplo synaptic. 

Supongo que pudes tenerla activada si tu opción es quitar el menu global para las aplicaciones de electron. Cuando la tienes que desactivar es si lo quieres hacer utilizando el enlace de webupd8.

**Comment by pablitok** [comment]
With that variable set, the globalmenu is missing, but is not showed 
inside the app either

**Comment by pablitok** [comment]
Ahh ok, el problema con la variable de entorno esa, es que quedo sin 
menu, ni en globalmenu, ni en el menu de la app en si,  no se si se 
entiende, si necesitas, te mando un screen de las 2 situaciones

**Comment by lestcape** [comment]
No te preocupes, pero vas a tener que esperarte un rato, ando en el trabajo. Acá no puedo probar nada, Te estoy diciendo lo que se supone que sea, pero la verdad ni idea de si actualmente funciona.

**Comment by lestcape** [comment]
Por favor baja la última versión de acá y prueba con esta, creo que tienes una version desactualizada que instalaste desde gnome extensions. Creo que slack, simplemente te va a funcionar si actualizas. Recuerdate que la extension esta no funciona en wayland.

**Comment by pablitok** [comment]
No hay apuro!
Mil gracias, amo tu extension, era lo unico que me faltaba para estar 
muy feliz con gnome shell, apenas tenga un tiempo libre voy a aprender 
a codear extensiones a ver si puedo contribuir un poco
Gracias!

**Comment by lestcape** [comment]
![captura de pantalla de 2017-08-18 15-37-04](https://user-images.githubusercontent.com/1389572/29476775-2fa9393c-842b-11e7-9839-12df5481c57c.png)

**Comment by pablitok** [comment]
Strange... is not working here... tonight I'll take a look, maybe I 
need to restart the shell or something, when I get to my house I'll try 
again
Thanks!

**Comment by lestcape** [comment]
I think you already resolve this.

**Comment by pablitok** [comment]
Hi Lester, I'm not sure if you should close this issue, because if I 
run slack as `ELECTRON_FORCE_WINDOW_MENU_BAR=1 slack`
The global menu is disabled, but the menu doesn't appear inside the 
window either

**Comment by lestcape** [comment]
ELECTRON_FORCE_WINDOW_MENU_BAR=1 is an indication to the electron application, not to the global menu extension. I'm not controlled this indication in any way. If you have some wrong experience with it, is not in my side the fix...

Regards.
