### ISSUE TITLE
Result in qt applications unthemed.

### ISSUE THREAD

**Issue by IsoaSFlus** [lestcape/Gnome-Global-AppMenu#62]
I used qt5ct to apply gtk theme on qt applications.But after I install this extension,qt applications on my system became unthemed(like without qt5ct).And then I found the $QT_QPA_PLATFORMTHEME had been changed to appmenu-qt5(formerly is qt5ct).Is it necessary that the extension changes $QT_QPA_PLATFORMTHEME?

**Comment by lestcape** [comment]
Read the information: https://launchpad.net/appmenu-qt5

**Comment by lestcape** [comment]
And i think you can see here your own answer: https://bugs.launchpad.net/appmenu-qt5/+bug/1667023
