### ISSUE TITLE
Discontinued for the moment.

### ISSUE THREAD

**Issue by lestcape** [lestcape/Gnome-Global-AppMenu#63]
Who want to continues with this extension can do it (really always), it's free software and the decision of discontinue it is pure personal. If one day I discover how to feel at ease with gnome and more specific with gnome shell for sure I will return to use it and maybe for this time Gnome will have a way to support this extension over Wayland (https://bugzilla.gnome.org/show_bug.cgi?id=784188), without that, this is a dead code. 

Outside the gnome shell, but inside its internal API I can find many of the things that have led me to love gnome, but with the recently break of standards (https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/) and more specific with the refusal to support other alternatives as a replace (https://bugzilla.gnome.org/show_bug.cgi?id=652122), gnome proved to me they will continues making things that I disapprove and the current way to do the things of gnome is 180 degrees out of my personal interest as a user, making me impossible to continues using gnome shell desktop.

I will want they will have always a successfully approval of all its faithful users. Gnome was and is to me a badge of free software, whatever they do, they are making it following the more strictly rules of what it mean Free Software, but also with all his love from sure.

But PERSONALLY, free software means to me: collaborate, support, help, provide, listen the users and developers, be inclusive. Free software not mean to me: break standards, only provide support for applications that follow his design rules, hidden options to the users, make private functionalists and/or libraries or take his own way not matter the discordance with other linux projects. Also not support what is clear something that most of users want to have.

I can not do extensions for all gnome functionalists that i want to have and they removed, further, If I want to try to feel at home with gnome, I am also limited by what gjs can do currently:(https://bugzilla.gnome.org/show_bug.cgi?id=786863).

Sorry for the inconvenience but I think it's better an explanation that nothing.

**Comment by lestcape** [comment]
Well see, not one is be able to fix this extension on Wayland only Gtk developers can do that. If they give an option, the global menu will have a hope in gnome.

I really don't see anyone trying to do something, so apparently is not important for anyone.

For X11 is working (more-less) and i think will continues be working for at less the next 6 month. I know the global menu is cool for lot of user, but i don't like it really and also I don't like the minimalist desktop designs of gnome. So, sorry for all that. 

I was not who decided remove the global menu for ubuntu, I just try to help as far as I can, but it is swimming against the flow of the river. Always comes the time when you get tired.

**Comment by jarryson** [comment]
hope ubuntu can do some magic thing about it.

**Comment by lestcape** [comment]
For the global menu I don't think they can do anything. For me sure (they are doing a lot of things), but i will wait to 18.04. There are some unstable protocols in Wayland, that probably could introduced some way to fix the global menu (but again just Gtk developers). I will wait for this protocols, but there are not really a warranty they can introduce a fix, i really don't know exactly for what i will be waiting as this not depend to me, and i will not continues fixing minors bugs if really there are not a solution in Wayland. Wayland is the close future.

But yes, if i will continues the global menu, will not be for gnome shell, will be for the ubuntu vision of gnome shell, so anyway I will not work to support gnome shell. I don't see the reason of contribute to gnome vanilla, as this break all his desktop conception, that apparently is so important.

**Comment by libReason** [comment]
It's hard when a project gets to a dead end, depending on other projects. True, I am still reading to know this issue better, and really hope the idea of a Global Menu on Gnome doesn't vanish. While I personally like many Gnome3 design features (like Epiphany's interface), I don't see much stardardization throughout other Gnome applications. Hope this is picked up by Canonical, but looking at the beta for Ubuntu 17.10, it looks to be a long road to get there..

**Comment by lestcape** [comment]
@libReason Yes, you could have reason, but what i think about why ubuntu will not make it is because this reasons:
1- They will not going to make patches for specific applications again.
2- The solution will be make a patch in gtk that they will need to keep update, because wayland is not stable yet.
3- To avoid more conflict with gnome.

**Comment by lestcape** [comment]
@libReason if you want to know better read the wayland issue. The problem is not here. The problem is to make the unity-gtk-module work in wayland. Is a gtk module, so directly depend of gtk.

**Comment by lestcape** [comment]
Please see, unity-gtk-module is a cannonical package that was removed from ubuntu 17.10: 
https://launchpad.net/unity-gtk-module

If some one is thinking ubuntu will do something:
Yes, they will do something they are removing the support for the global menu and also see:
https://didrocks.fr/2017/08/03/ubuntu--guadec-2017-and-plans-for-gnome-shell-migration/#comment-3473026578

**Comment by lestcape** [comment]
The author of the blog (Didier Roche) is a cannonical developer and he is the top contributor of unity-gtk-module

**Comment by HEXcube** [comment]
Really unfortunate to see this extension enter a hiatus. I hope GNOME or Ubuntu does something to bring Global Menu support on Wayland.

On second thought GNOME might not really care about menus, coz all official GNOME Apps don't have regular menus anymore (they only have GNOME's new AppMenus). However, lots of regularly used apps (like LibreOffice, GIMP, Inkscape and almost all the Qt and KDE apps) do heavily use menus.

**Comment by libReason** [comment]
@lestcape Thanks for all the info. I'll look into more details and learn all the key issues. It would also be good if there was a way to automatically convert standard menus (like LibreOffice, GIMP, etc.) into Gnome AppMenus too. Hope to see this fixed soon, I used to have global menus a lot.

**Comment by lestcape** [comment]
@HEXcube is like you say and for that reason, like really a clean solution only can come from gtk developers (gnome developers) and not for ubuntu (like ubuntu only can patch gtk), this is a dead extensions. Pretty sure, without a celestial miracle, will continue be a dead code.

**Comment by lestcape** [comment]
If there are a way to hack a gdk function inside a gtk module, could be also possible that this work.

The normal procedure to hack a library function is play with the order of how a library is loaded using the `LD_PRELOAD` trick, but in this context the gtk module is a module of the library itself. If someone discover how to hack externally to gtk module code (from the whole gtk) the function:

`gdk_wayland_window_set_dbus_properties_libgtk_only`

Will be possible try to do something.

In my test i can only be able to hack the function to be used by the unity-gtk-module code, but what is need is redirect the all calls to a wrapper function and not only the call that occurs inside unity-gtk-module.

If someone discover how to do that, please i'm listen here.

**Comment by rilian-la-te** [comment]
May not hack this function, but try to use it to our own advantage? 
For example, set_window_data in unity-gtk-module will be occurs before call of this function, and it consumes a results...
When on GtkWindow init sequence this function is used?

**Comment by lestcape** [comment]
Yes, this is the reason of why i need to interest this call. The only place where is called is here:
https://github.com/GNOME/gtk/blob/4724a89022ef1bec93b1a42d4cf2fec7191ed712/gtk/gtkapplication-wayland.c#L54

Exactly in the middle of the GtkWindow realize (i don't know what is the init to you, if the realize is part of the init yes).

If we can intercept this call and override it, sending to the real function our own parameters instead of the default. it of course will work.

Now that you are here, i remember that i also try your idea of find the active window and use it. See what i found trying, it will be interesting to you:
https://github.com/ActivityWatch/activitywatch/issues/92

For another hands, also if you don't need to get the active/focused windows, but instead you need active one, please see:
https://bugzilla.gnome.org/show_bug.cgi?id=766284

Anything where i see, there are problems and limitations :(

**Comment by lestcape** [comment]
If you call this function before the realize, you don't have the default data and you will override things with nothing valid and also the windows is not realize so it will create a problem when the windows will be realize. If you call this function after the realize, then your data will not be set, because gtk prevent set this data more than one time. So, the only solution to me outside a change in gtk is intercept the call and i can not be able to do that. I think is not possible.

**Comment by lestcape** [comment]
Another possibility is here: https://github.com/GNOME/gtk/blob/0bdaebef1ebfc9ff221ed0222c67378da3814856/gdk/wayland/gdkwindow-wayland.c#L2521

They change the value of was set, if we can be able to execute this code we can change the value and try to set our values in that place, but we have not the default value, so we will override things witch nothing valid... We need the default values!!!

**Comment by rilian-la-te** [comment]
we can hijack ```gdk_wayland_window_set_dbus_properties_libgtk_only``` itself? Because if we can do it in Gtk module, we can exactly do what we want.

**Comment by rilian-la-te** [comment]
AFAIK, we need to hijack GtkWaylandWindow

**Comment by rilian-la-te** [comment]
So, it we hijack this function (maybe I will add support of it to appmenu-gtk-module), we can control a menu and need only to select standard path to UNITY_GTK_ACTION_GROUP prop (it is not in gtk_shell)

**Comment by lestcape** [comment]
@rilian-la-te  yes. Thats way i say:

` If someone discover how to do that, please i'm listen here.`

**Comment by lestcape** [comment]
Read this: https://github.com/lestcape/Gnome-Global-AppMenu/issues/63#issuecomment-330391673

**Comment by lestcape** [comment]
Maybe we need to ask in stackoverflow if there are a way to hack this in our context. The gdk function is not a property of any object and is not called from any object, is a library function, so the same procedure to hijack object functions won't work in that case.

**Comment by khurshid-alam** [comment]
@lestcape 

[Copied from omgubuntu comments in case you don't read that]

> Ubuntu is using patched shell. And the global menu is very much under their radar. 
> 
> Shell couldn't use netbook power-button to shutdown computer. But did it bother Dell, hP, System76? No. Because they went with Ubuntu which can. So What's 180 degree out of way in Gnome, falls inline with Ubuntu. So don't let bother you what's Gnome's way or not. There is no such thing as "Gnome's way", because Gnome is not an OS. It's a project of hundreds of different pieces. It's just that Fedora chooses certain default things at compilation (as RH uses fedora but no one else ,hell even Ubuntu was spotted in RH many times!!) and call it default Gnome, but that is all there is.  
> 
> You can think Ubuntu as default Gnome and move on. 20 million people uses Ubuntu. There is a plan to port unity-gtk-module to wayland. But there is a 10 years old compositor bug (or just another non nonsensical security issue? ) which is preventing Ubuntu to make that happen. I heard some Korean developers want to fix those old bugs and RH was talking with them. So hopefully it will get fixed.
> 
> But you should focus on Ubuntu. If Ubuntu takes your code makes it upstream, everyone will benefit from that.

> Hence I sincerely request you to revisit your decision. Anyway, Thanks for giving us this awesome extension. Hopefully you will still find some time to maintain it for X11.

**Comment by dobkeratops** [comment]
I hope the gnome shell people understand how important global menu is, they need to be supportive of it

**Comment by lestcape** [comment]
@khurshid-alam it will be good if they can do something, i also tried to solved this as you can see, but i can not make any progress. Sorry for me incompetence. If i can help in something I'm here.

**Comment by timofonic** [comment]
@lestcape I'm really sorry. The global menu is one of the things I like from AmigaOS/MacOS/AtariTOS :(

**Comment by lestcape** [comment]
@timofonic That's can be solved, is not a thing of lamentations. If you and all want to have a feature, the normal reaction is request what you want to who can add it. I think all developers have a common sense and they listen users. Then, what is in our hands is request what you need. If it's something that a lot of users want and really can be done, at least if they have a common sense, this need to be implemented.

It is in our hands request what we want at least. If we don't request what we want, we never could be able to get it. So, at least you can joined to the request or contribute to expose reason of why that is needed of why will be a good think to have: https://bugzilla.gnome.org/show_bug.cgi?id=784188

**Comment by MeleTest** [comment]
@letscape Today, i used the gnome wayland session and your globalmenu is still working. Not as fluently as on xorg session, but it works. I am on debian stretch. Am I wrong?

**Comment by lestcape** [comment]
@MeleTest It will not work for Gtk applications, but it will work for others. I fixed it most i can to a point where if unity-gtk-module will be fixed without to change any external interface all will be working in the extension automatically. In other words, there are not an impediment here. The problem is the Gtk applications only for now, Non Gtk applications are not Wayland applications yet, so they they are X11 applications that works embedded inside Wayland as XWayland applications. How they are X11 applications there are not problem for it. the problem are Wayland applications only, with mean Gtk applications only for now.

Will be good if you share how you install unity-gtk-module on Debian, sure there are people that want to know, how to do that.

**Comment by MeleTest** [comment]
@letscape Your are right, Gtk applications don't work or will scratch.
Installing the globalmenu on debian is a matter of library version. For example stretch librairies version match with Ubuntu Trusty's one. So you need to

1- Add to "/etc/apt/sources.list" the foloowing lines
#firefox with global menu support
deb http://security.ubuntu.com/ubuntu/ trusty-security main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu trusty-updates main restricted universe multiverse

2- Avoid to break your installation with unwanted ubuntu's software by creating a pining file (for example "/etc/apt/preferences.d/ubuntu-pining"). You need to remove debian firefox_esr and replace it with ubuntu's one. So the pining file will look like this:

Package: *
Pin: release v=14.04,o=Ubuntu
Pin-Priority: 50

Package: *firefox*
Pin: release v=14.04,o=Ubuntu
Pin-Priority: 500

3- Then just install
#> apt-get update
#> apt-get install firefox firefox-locale-XX unity-gtk2-module unity-gtk3-module

where XX is your langage code

4- Install the globalmenu extension, enable it and voilà.

5- You can the remove firefox_esr* if needed
If you need an other package from ubuntu, just edit your pining file to add the three lines like for firefox.

**Comment by lestcape** [comment]
@MeleTest Thanks.

**Comment by himanshuxd** [comment]
@MeleTest Can you tell me what the following does in the pinning file : 
`Package: *
Pin: release v=14.04,o=Ubuntu
Pin-Priority: 50`

**Comment by MeleTest** [comment]
@himanshuxd 
This means that all packages from ubuntu v14 are given a weight of 50 which is low compared to the default release (debian) that have a weight of 500, so they won't be installed, except (Package: *firefox*) firefox packages which has been given a weight of 500. So all firefox packages that does not exist in debian release or which have higher version number that debian one's will be installed.

**Comment by lestcape** [comment]
The extension is not anymore discontinued.

_**Was added initial support for Wayland.**_

The code to support Wayland can be found here: https://github.com/lestcape/unity-gtk-module It's just tested on Ubuntu 16.04 and probably will not work on any other places. The change will be merged with theimplementation of @rilian-la-te of his vala-panel-appmenu (https://github.com/rilian-la-te/vala-panel-appmenu), as this package is distribute on most of linux distros. You are free to copy this implementation and port it to the place you want, but the gnome global menu will STOP to used the unity-gtk-module in favor of the fork of unity-gtk-module of @rilian-la-te, as this implementation it's more general and is supported in more linux distibutions.

**Known issues of the global menu on Wayland:**

  -  The menu dosen't not work in the gnome-terminal application, as there are not support on gnome wayland for the gtk-shell-show-menubar property of the gtk settings when we use the XSettings binding.
   - The menu will not work for windows that are not a GtkApplicationWindow.

**Comment by HEXcube** [comment]
Glad to see the blocking Wayland issue resolved and the extension moving ahead. :relaxed:  This brings hope for using GNOME with Global Menu on newer distros.

**Comment by lestcape** [comment]
@akalongman yes, you can. It's also merged with the appmenu-gtk-module fork of unity, but it's not working well if you use the ubuntu Wayland session with appmenu-gtk-module and also is not working at all if you used unity-gtk-module. It probably will work in wayland if you installed the appmenu-gtk-module from the source, but remaining untested. The initial support for appmenu-gtk-module was added yesterday.

![captura de pantalla de 2018-04-30 10-43-05](https://user-images.githubusercontent.com/1389572/39436337-4d6b06fc-4c63-11e8-996f-c47f00f3e1be.png)

**Comment by akalongman** [comment]
@lestcape on your screen I see title bar and what is a point of the global app menu if you still have a separate line of the title bar and window buttons?

**Comment by lestcape** [comment]
@akalongman What is the point on use a Linux distro if it's not Mac OS? Do you know that a global menu and the ability to remove the windows titlebars are not the same thing rigth?

This is just a global menu and not more than that. I don't force anyone to use it. So, the point is that there are a global menu on gnome shell to whatever that want to used it, not more not less.

There are other extensions in gnome to remove the titlebar. If you use both toggeder you will archived probably the behaviour that you are looking for...

**Comment by akalongman** [comment]
@lestcape sorry if my comment was a little bit confusing, this extension is very useful and thank you for your work. 
I wanted to say that if the main point of the extension was making the Gnome menu like old good Unity, then it needs the ability of hiding title bar and removing controls to the left side which also will be integrated to the top menu. See the screen:
![2018-04-30_21 17 31](https://user-images.githubusercontent.com/423050/39440468-07b22a88-4cbc-11e8-9f4b-128d8976df22.jpg)

> There are other extensions in gnome to remove the titlebar. If you use both toggeder you will archived probably the behaviour that you are looking for...

I will try, thank you. But I think its still not what I want (make Gnome like Unity)

**Comment by lestcape** [comment]
@akalongman I don't like the global menu, i don't like gnome-shell and also i don't like unity. What i really like are desktops like cinnamon or mate or kde.

I'm ofcourse not make this to to meet your requirements, but you have something working and is free. So, fork it and modify it like you want.

**Comment by lestcape** [comment]
@akalongman if what you want can be added as an option, feel free to create a pull here, if is not easy in that way and you want to understand something of this code to do what you want externally, just open a new issue, I will try to help you if i can.

Just to save you some time:
 1- Gnome is adding the possibility to render Gtk4 components using opengl and vulkan, so probably clutter will be disappear from the shell in the future, in favour of Gtk4 and then could be better invert time in a Gtk base component instead of lost time here.
  2- The whole gnome is in migration to use CSD, where thing like this are not allowed and then are more like against of what gnome want.
  3- Whatever you want to do here will also depend of what the specific developer of an application want to let you to do, what the shell itself want to let you and also the toolkit (Gtk). As this is an extension we can not modify the specific applications to full-fill our requirements.
  4- The whole linux ecosystem is in migration to Wayland and there are not yet support for Qt Wayland application inside Gnome. So, is not clear at all what will happen and if will have or not a way to have a global menu for Qt Wayland applications inside gnome.

And the things are not much more different for extensions with the possibility to remove the title bar for the future:
https://github.com/deadalnix/pixel-saver/issues/32
