### ISSUE TITLE
Global Menu does not work on VSCode

### ISSUE THREAD

**Issue by luisgarciaalanis** [lestcape/Gnome-Global-AppMenu#66]
I installed ubuntu 17.10, and this extension.

I installed Microsoft Visual Studio Code and the menus sometimes apear, sometimes they do not, but they are still removed from VSCode.

**Comment by lestcape** [comment]
Please see if you are using the lasted version of vscode and gnome global menu. Apparently, as also VSCode conflict with the kde global menu:
https://github.com/Microsoft/vscode/issues/33166

As a temporal solution, if you want to have the extension enable, execute the VSCode with the ubuntu menu proxy environment variable disabled:

`UBUNTU_MENUPROXY=0 /opt/vscode/Code`

You can find more information about how to disable the global menu for specific applications online. Please note, this procedure could be incompatible with the first experimental option of the global menu settings (the option that required root privileges to change your environment statically).

Thanks and regards.

**Comment by lestcape** [comment]
I suppose that you solved your problem with VSCode. So, i will close it, but feel free to commented here to be reopened if the problem occurs with the last version of VSCode and this extension.
