### ISSUE TITLE
Freezes GNOME Shell when LibreOffice is running

### ISSUE THREAD

**Issue by jonnius** [lestcape/Gnome-Global-AppMenu#67]
If this extension is enabled and LibreOffice is running the Gnome Shell freezes.

**Comment by lestcape** [comment]
Thanks and see... All in Gnome run in the same thread, when you open an applications, the compositor need to realized a lot of task and also at the same time the extension request the menu and try to build it in the same thread where the compositor is working. This is then an architecture issue of gnome shell itself. They want to have all in the same thread and this then just one of the several inconvenience that the gnome-shell monolithic architecture have.

What could be on the hands of the extension is observe the application and wont request the menu until the application is alive (the compositor end his task and the application was displayed). If i do that you will see the menu probably 1 or tow minutes before you open the application.

So, if you have a good solution of this problem, here are the issues related with the monolithic architecture of Gnome Shell:

https://bugzilla.gnome.org/show_bug.cgi?id=745032
https://bugzilla.gnome.org/show_bug.cgi?id=687362

As you can read there, they not want to solved the issue of the wrong architecture of Gnome, just only they want to mitigate in all case what the user can see and continues with his wrong architecture. So, i think this will not have a solution then. Sorry.

**Comment by lestcape** [comment]
I do my part. Now i check if the application is busy first, then this need to work a little better now: https://github.com/lestcape/Gnome-Global-AppMenu/commit/1eb8444c2279d48fe1368590424d1bc480e7a55d

You also can see this block of code:
https://github.com/lestcape/Gnome-Global-AppMenu/blob/master/gnomeGlobalAppMenu%40lestcape/extensionManager.js#L815-L830

If you remove the comment for this 2 lines:
https://github.com/lestcape/Gnome-Global-AppMenu/blob/master/gnomeGlobalAppMenu%40lestcape/extensionManager.js#L817-L818

and this another 3 lines:
https://github.com/lestcape/Gnome-Global-AppMenu/blob/master/gnomeGlobalAppMenu%40lestcape/extensionManager.js#L817-L818

then save and restart the shell, when you open the libre office, you will notice that is more responsive now. The code is executed in the same thread but with a delay, to wait for the compositor.

You can move this value https://github.com/lestcape/Gnome-Global-AppMenu/blob/master/gnomeGlobalAppMenu%40lestcape/extensionManager.js#L817 to adjust it to your specific hardware. But see, this will not work for Qt application so... Is just to be tested for gtk application, to see what really is happen there and why i say that this is a Gnome wrong architecture.
