### ISSUE TITLE
Question/feature request: any way to put global menu after GNOME menu?

### ISSUE THREAD

**Issue by nkkollaw** [lestcape/Gnome-Global-AppMenu#79]
I actually like the GNOME menu, it has the "quit" command and spinner.

Is there any way to put the global menu after the GNOME menu (so, to the right), and perhaps disable the possibility to close it?

I'd like to keep the GNOME menu and simply add a global menu next to it that always stays there without closing.

Another option would be to add a settings for the action to perform when you click on the application name: show/hide the global menu, or show the application menu.

I LOVE this extension!!

**Comment by lestcape** [comment]
No, there are not a way to put the global menu after or before any other button of the panel. It's fixed always in the same position.

Is nothing special to me the appmenu, like it's another more button of your panel. So, your proposition it's probably the think that i dislike more about gnome-shell. There are not way (like for example cinnamon), to decide where i want my buttons.

So like you want to change the buttons position. Do you not think this is a request for the shell itself and not for this extension? 

Of course i can not depend of things that can be there or can not, or probably another extension move it to other place. This request is by definition a shell task. Also see:
https://github.com/lestcape/Gnome-Global-AppMenu/issues/45

Regards.

**Comment by nkkollaw** [comment]
I see. 

What do you think about the second part of my comment: a setting that allows showing the app menu ("quit", sometimes "preferences") instead of hiding the global menu when you click on the application name?

**Comment by rilian-la-te** [comment]
If you will get all menus as MenuModels, you can combine it at will, so, you can add a parts of appmenu to your MenuModel of menubar. And show it compactly (Like I done in my compact mode in 0.7.0). If I am right, Gnome-Shell can handle MenuModels (it has a method for this).

**Comment by nkkollaw** [comment]
In the settings, you could choose:

1) Show the global menu:
a) inside the panel
b) when you click on the application name

2) When you click on the application name
a) show the global menu
b) show the application menu 

Question 2) would only be visible/enabled if you picked "a" in question 1)

**Comment by lestcape** [comment]
@rilian-la-te not at all. The menu that you see is render by my own code and have not support from thinks like that. It will be a lot of work.

**Comment by lestcape** [comment]
@nkkollaw you get the idea of my question, but or i don't understand your proposition or you don't see the option of render the menu outside the panel what is doing.

Specifically:
In _1-Show the global menu_ the options **a** and **b** are not mutually exclusives.

So, i can show the menu inside the panel and at the same time when i click the application name.

**Comment by rilian-la-te** [comment]
@lestcape you do not using GMenuModel and GtkMenuTracker like shell builtin appmenu?

**Comment by rilian-la-te** [comment]
If not, why?

**Comment by lestcape** [comment]
@rilian-la-te yes, but for the appmenu only. I translate the appmenu in a shell menu, but i never construct a GMenuModel from the menubar, to then use it... Gnome Shell do not provide one GMenuModel for the menubar it just provide a GMenuModel for the appmenu. Interesting not? They only support what they want.

**Comment by rilian-la-te** [comment]
But you able to create GMenuModel from menubar object path via Gnome-Shell (via GLib binding)?

**Comment by lestcape** [comment]
@rilian-la-te i don't try to do this in that way, but probably i can create a menu using the GMenu implementation of a GmenuModel.

**Comment by rilian-la-te** [comment]
If you can create it using ```g_dbus_menu_model_get()``` as in C (in GJS we also have similar function, I think), so, you can have menubar menumodel.

**Comment by rilian-la-te** [comment]
And then you need a translator and you can then have GMenuModel from DBusMenu objects also.

**Comment by lestcape** [comment]
The architecture that i use is:
I have a shell API, and I have some special menu shell components that can be build form a Menu representation.

Finally I have a builder that build the menu base on the representation, taking on account if the item change or not. This is a big improve in performance, because i don't render an item that was currently render.

In gnome they don't have currently something like that. The appmenu is rendering again for a very little changes currently (also in my implementation, as is a fork of the gnome one).

If i use the gnome way, i will freezes the whole shell.

**Comment by rilian-la-te** [comment]
I do not understand Gnome Shell so deep, sorry. I was thinking than it is like GTK: you can have GMenuModel (from some GJS Method) and then bind it to shell's appmenu component.

**Comment by lestcape** [comment]
It's probably possible, but it's not implemented yet. See: https://bugzilla.gnome.org/show_bug.cgi?id=792262#c1

**Comment by nkkollaw** [comment]
@letscape: I had edited my comment 5 seconds after posting, your reply looks like to the original comment.

**Comment by lestcape** [comment]
@nkkollaw i see... The question was how handle it in both scenarios. Not how to handled it just in one scenario (the menu inside the panel is just one scenario). I don't want to create specific cases like that because this is more patches for the extension. Also the extension settings not work in that way (you can not, hidden a block of questions).

**Comment by nkkollaw** [comment]
I understand.

Oh well, I'll live with this.

**Comment by lestcape** [comment]
@nkkollaw Not worried, i want to make a thing like that also, but not to add just a quit menu. I want that be possible add the whole application menu (in a traditional way). Just it's not the time to make a change like that.
