### ISSUE TITLE
Default setting breaks alt+tab (and possibly other key combos)

### ISSUE THREAD

**Issue by hanjiexi** [lestcape/Gnome-Global-AppMenu#8]
Hi,

Gnome Global AppMenu, by default, sets "Keyboard shortcut to open and close the menu" to Alt_L (left Alt). Now when you try to press Alt+Tab to switch between applications, it instead just opens the menu. A temporary workaround is to set the keyboard shortcut to Alt_R (right Alt) and use that as a shortcut for opening the menu.

But, this behavior is not ideal. The menu shouldn't be opened until the left Alt key is *released*, and the extension should completely ignore the keypress if the user instead decides to do an Alt+Tab, or some other Alt combo.

**Comment by lestcape** [comment]
Yes the alt it's a complicate key as it's also a mask. It's where i actually are working. I try to find a way for bypass the gnome grabber for key-bindings. The global menu is a common pleases, not just a less used menu, so not matter the state of gnome shell, the hotkey need to work, and it's not working. It's pretty confused to me, please see: https://bugzilla.gnome.org/show_bug.cgi?id=778809

**Comment by lestcape** [comment]
https://github.com/lestcape/Gnome-Global-AppMenu/commit/d46769f63ac1cfa6ad8754f4caa2240916252bee
