### ISSUE TITLE
IntelliJ 2018 (Jayatana) support on Ubuntu 18.04

### ISSUE THREAD

**Issue by vali20** [lestcape/Gnome-Global-AppMenu#83]
Hi
I have enabled Jayatana support in the config panel, and also added the line:
`-javaagent:/usr/share/java/jayatanaag.jar`
in idea64.vmoptions config file for IntelliJ. The menu does not appear in the IntelliJ window, and it is apparently exported, but does not show in the top panel, in this extension.
And sometimes it just fails loading the designer and you have to restart the IDE ("Fatal error initializing plugin com.intellij.uiDesigner").
Any advice on how to fix this?
Thanks, excellent work btw.

**Comment by rilian-la-te** [comment]
Intellij has very big menu, and Jayatana has a very unoptimized architecture. So, maybe @lestcape 's applet just cannot load this biggy menu, which reloads after each click (because gnome-shell JS, AFAIK, has only one thread).

What it write to console? Do it works with Jayatana demo app?

@lestcape , sorry. But I also have Jayatana.

**Comment by vali20** [comment]
Would have tried the demo app, should I had known about it. Where do I find the jar file? Or do I have to compile from source?

**Comment by rilian-la-te** [comment]
I use Warlords4Editor as demo.

**Comment by lestcape** [comment]
The last time I tested it was a long time ago... In X11, the id of the x window of the java app was incorrectly  in the application initialization and it could fail... A restar of the shell, after open the aplication will display the menu properly.

If you have installed jayantana is supposed that you don't need to do anything just enable the support in the settings. It's of course untested with the @rilian-la-te fork, but sure it's recommended use it instead of the default (as is buggy).

**Comment by vali20** [comment]
Okay, so you're saying that I should compile the source here: https://github.com/rilian-la-te/java-swing-ayatana and use that instead of what Ubuntu ships with by default? It seems a bit old to me.

@rilian-la-te I cannot find the jar file, unfortunately...

Thanks for your help.

**Comment by rilian-la-te** [comment]
@vali20,no, this is a wrong repo. You should go to https://github.com/rilian-la-te/vala-panel-appmenu/tree/master/subprojects/jayatana and compile it.

**Comment by vali20** [comment]
@lestcape Okay, I was just playing around with it as I plan on migrating from 16.04 to 18.04. It is great to see that this is still developed and worked on, and honestly I have to say that this should be part of the distro in itself. Having global menus helps for productivity if you're accustomed to working that way. So yeah, my appreciation for your efforts and many thanks for what the excellent utility you are developing.

@rilian-la-te Sorry to ask again, but any idea on how to compile? The readme is short and does not provide any info on this, and I am not that experienced. Thanks.

**Comment by rilian-la-te** [comment]
@vali20
1. Clone repo https://github.com/rilian-la-te/vala-panel-appmenu.git
2. cd to subprojects/jayatana
3. mkdir build && cd build
4. cmake .. -DCMAKE_INSTALL_PREFIX=/usr
5. make
6. sudo make install

**Comment by vali20** [comment]
@rilian-la-te Sorry, but it just says `make: *** No rule to make target 'install'.  Stop.`. Also, I think something is wrong with the CMakeLists.txt, as it gives the following output when I run [4]:

-- Checking for module 'gir1.2-dbusmenu-glib-0.4>=16.04.0'
--   No package 'gir1.2-dbusmenu-glib-0.4' found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/valentin/Desktop/vala-panel-appmenu/subprojects/jayatana/build

Thanks for your help.

**Comment by rilian-la-te** [comment]
You need to install gir1.2-dbusmenu-glib-0.4 from your repo (sorry, I do not know exact name of package).

**Comment by vali20** [comment]
The issue is I already have it installed...

**Comment by rilian-la-te** [comment]
Show me a full cmake log then.

**Comment by lestcape** [comment]
@vali20 you can tested java apps now. But also if they can work, don' t think they will work ok....

**Comment by lestcape** [comment]
![captura de pantalla de 2018-05-03 08-39-23](https://user-images.githubusercontent.com/1389572/39579930-89ac8a9a-4ead-11e8-8677-7522b7fca7bd.png)

**Comment by Pitometsu** [comment]
@rilian-la-te 
```
vala-panel-appmenu/subprojects/jayatana$ mkdir build && cd build
vala-panel-appmenu/subprojects/jayatana/build$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr
-- The C compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Java: /usr/lib/jvm/java-8-oracle/bin/java (found version "1.8.0_171") 
-- Found JNI: /usr/lib/jvm/java-8-oracle/jre/lib/amd64/libjawt.so  
-- Configuring done
-- Generating done
-- Build files have been written to: vala-panel-appmenu/subprojects/jayatana/build
vala-panel-appmenu/subprojects/jayatana/build$ make
vala-panel-appmenu/subprojects/jayatana/build$ sudo make install
make: *** No rule to make target 'install'.  Stop.
vala-panel-appmenu/subprojects/jayatana/build$ sudo make all
$ ls /usr/share/java/jayatanaag.jar
ls: cannot access '/usr/share/java/jayatanaag.jar': No such file or directory
```

**Comment by Pitometsu** [comment]
@rilian-la-te not sure, how can I check it? Any `configure`?

**Comment by rilian-la-te** [comment]
Installed packages, please. It is a first time when I see this error.

**Comment by Pitometsu** [comment]
` libxkbcommon-dev libdbusmenu-glib-dev libx11-dev libxt-dev oracle-java8-installer`

**Comment by rilian-la-te** [comment]
Do you have also OpenJDK installed? It says than it cannot find a UI definitions, so, it definitely a theme. Your Idea cannot find a GTK theme AFAIK.

**Comment by Pitometsu** [comment]
Without `JAVA_TOOL_OPTIONS` it just works, without errors, but with no global menu support. That's why I try to force it to use jayatana.

**Comment by Pitometsu** [comment]
No, I have no OpenJDK here.

**Comment by rilian-la-te** [comment]
Can you try to use Adwaita?
And can you show me a build log?

**Comment by Pitometsu** [comment]
I didn't changed ubuntu default gtk theme.

**Comment by Pitometsu** [comment]
```
$ make
[  6%] Building Java objects for jayatana-java.jar
[ 13%] Generating CMakeFiles/jayatana-java.dir/java_class_filelist
[ 20%] Creating Java archive jayatana.jar
[ 20%] Built target jayatana-java
[ 26%] Building C header files from classes...
[ 26%] Built target java-headers
Scanning dependencies of target jayatana
[ 33%] Building C object lib/CMakeFiles/jayatana.dir/com_jarego_jayatana_basic_GlobalMenu.c.o
[ 40%] Building C object lib/CMakeFiles/jayatana.dir/com_jarego_jayatana_basic_GMainLoop.c.o
[ 46%] Building C object lib/CMakeFiles/jayatana.dir/com_jarego_jayatana_collections.c.o
[ 53%] Building C object lib/CMakeFiles/jayatana.dir/com_jarego_jayatana_jkey2xkey.c.o
[ 60%] Building C object lib/CMakeFiles/jayatana.dir/com_jarego_jayatana_jni.c.o
[ 66%] Linking C shared library libjayatana.so
[ 66%] Built target jayatana
Scanning dependencies of target jayatanaag
[ 73%] Building C object lib/CMakeFiles/jayatanaag.dir/com_jarego_jayatana_Agent.c.o
[ 80%] Linking C shared library libjayatanaag.so
[ 80%] Built target jayatanaag
Scanning dependencies of target agent-java
[ 86%] Building Java objects for agent-java.jar
[ 93%] Generating CMakeFiles/agent-java.dir/java_class_filelist
[100%] Creating Java archive jayatanaag.jar
[100%] Built target agent-java
vala-panel-appmenu/subprojects/jayatana/build$ sudo make install
[sudo] password for yuriypitomets: 
[ 20%] Built target jayatana-java
[ 26%] Built target java-headers
[ 66%] Built target jayatana
[ 80%] Built target jayatanaag
[100%] Built target agent-java
Install the project...
-- Install configuration: ""
-- Installing: /usr/lib/x86_64-linux-gnu/jayatana/libjayatana.so
-- Set runtime path of "/usr/lib/x86_64-linux-gnu/jayatana/libjayatana.so" to ""
-- Installing: /usr/lib/x86_64-linux-gnu/jayatana/libjayatanaag.so
-- Set runtime path of "/usr/lib/x86_64-linux-gnu/jayatana/libjayatanaag.so" to ""
-- Installing: /usr/share/java/jayatana.jar
-- Installing: /usr/share/java/jayatanaag.jar
vala-panel-appmenu/subprojects/jayatana/build$ 
```

**Comment by rilian-la-te** [comment]
And CMake options used, please.

**Comment by Pitometsu** [comment]
```
vala-panel-appmenu/subprojects/jayatana$ mkdir build && cd build
vala-panel-appmenu/subprojects/jayatana/build$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr
-- The C compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Java: /usr/lib/jvm/java-8-oracle/bin/java (found version "1.8.0_171") 
-- Found JNI: /usr/lib/jvm/java-8-oracle/jre/lib/amd64/libjawt.so  
-- Checking for module 'xkbcommon'
--   Found xkbcommon, version 0.8.0
-- Checking for module 'dbusmenu-glib-0.4>=16.04.0'
--   Found dbusmenu-glib-0.4, version 16.04.0
-- Configuring done
-- Generating done
-- Build files have been written to: vala-panel-appmenu/subprojects/jayatana/build
vala-panel-appmenu/subprojects/jayatana/build$ make
Scanning dependencies of target jayatana-java
[  6%] Building Java objects for jayatana-java.jar
[ 13%] Generating CMakeFiles/jayatana-java.dir/java_class_filelist
[ 20%] Creating Java archive jayatana.jar
[ 20%] Built target jayatana-java
Scanning dependencies of target java-headers
[ 26%] Building C header files from classes...
[ 26%] Built target java-headers
Scanning dependencies of target jayatana
[ 33%] Building C object lib/CMakeFiles/jayatana.dir/com_jarego_jayatana_basic_GlobalMenu.c.o
[ 40%] Building C object lib/CMakeFiles/jayatana.dir/com_jarego_jayatana_basic_GMainLoop.c.o
[ 46%] Building C object lib/CMakeFiles/jayatana.dir/com_jarego_jayatana_collections.c.o
[ 53%] Building C object lib/CMakeFiles/jayatana.dir/com_jarego_jayatana_jkey2xkey.c.o
[ 60%] Building C object lib/CMakeFiles/jayatana.dir/com_jarego_jayatana_jni.c.o
[ 66%] Linking C shared library libjayatana.so
[ 66%] Built target jayatana
Scanning dependencies of target jayatanaag
[ 73%] Building C object lib/CMakeFiles/jayatanaag.dir/com_jarego_jayatana_Agent.c.o
[ 80%] Linking C shared library libjayatanaag.so
[ 80%] Built target jayatanaag
Scanning dependencies of target agent-java
[ 86%] Building Java objects for agent-java.jar
[ 93%] Generating CMakeFiles/agent-java.dir/java_class_filelist
[100%] Creating Java archive jayatanaag.jar
[100%] Built target agent-java
vala-panel-appmenu/subprojects/jayatana/build$ sudo make install
[sudo] password for yuriypitomets: 
[ 20%] Built target jayatana-java
[ 26%] Built target java-headers
[ 66%] Built target jayatana
[ 80%] Built target jayatanaag
[100%] Built target agent-java
Install the project...
-- Install configuration: ""
-- Installing: /usr/lib/x86_64-linux-gnu/jayatana/libjayatana.so
-- Set runtime path of "/usr/lib/x86_64-linux-gnu/jayatana/libjayatana.so" to ""
-- Installing: /usr/lib/x86_64-linux-gnu/jayatana/libjayatanaag.so
-- Set runtime path of "/usr/lib/x86_64-linux-gnu/jayatana/libjayatanaag.so" to ""
-- Installing: /usr/share/java/jayatana.jar
-- Installing: /usr/share/java/jayatanaag.jar
vala-panel-appmenu/subprojects/jayatana/build$ 
```
Tried change Idea UI theme to Gtk+ with no luck - jayatana still not working.

**Comment by rilian-la-te** [comment]
Can you try OpenJDK?

**Comment by Pitometsu** [comment]
In output still the same:
```
...
UIDefaults.getUI() failed: no ComponentUI class for: javax.swing.JScrollPane$ScrollBar[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=4194304,maximumSize=,minimumSize=,preferredSize=,blockIncrement=10,orientation=VERTICAL,unitIncrement=1]
java.lang.Error
	at javax.swing.UIDefaults.getUIError(UIDefaults.java:730)
	at javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:130)
	at javax.swing.UIDefaults.getUI(UIDefaults.java:760)
	at javax.swing.UIManager.getUI(UIManager.java:1016)
	at javax.swing.JScrollBar.updateUI(JScrollBar.java:227)
	at javax.swing.JScrollBar.<init>(JScrollBar.java:161)
	at javax.swing.JScrollBar.<init>(JScrollBar.java:176)
	at javax.swing.JScrollPane$ScrollBar.<init>(JScrollPane.java:718)
	at javax.swing.JScrollPane.createVerticalScrollBar(JScrollPane.java:873)
	at javax.swing.JScrollPane.<init>(JScrollPane.java:299)
	at javax.swing.plaf.basic.BasicComboPopup.createScroller(BasicComboPopup.java:571)
	at javax.swing.plaf.basic.BasicComboPopup.<init>(BasicComboPopup.java:335)
	at javax.swing.plaf.basic.BasicComboBoxUI.createPopup(BasicComboBoxUI.java:433)
	at javax.swing.plaf.basic.BasicComboBoxUI.installUI(BasicComboBoxUI.java:250)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JComboBox.setUI(JComboBox.java:257)
	at javax.swing.JComboBox.updateUI(JComboBox.java:266)
	at javax.swing.JComboBox.init(JComboBox.java:231)
	at javax.swing.JComboBox.<init>(JComboBox.java:225)
	at org.jetbrains.plugins.scala.editor.autoimport.ScalaAutoImportOptionsProviderForm.$$$setupUI$$$(ScalaAutoImportOptionsProviderForm.java:98)
...
```

**Comment by lestcape** [comment]
@Pitometsu it's working with the jayatana in the default ubuntu repositories, or at less it need to work...

If is not working will be really more difficult that it will work with the @rilian-la-te fork. The @rilian-la-te fork, is just optimized to work better, but will required, that you install it manually. I think is preferable ensure it work with the default ubuntu version and then try to use the @rilian-la-te fork, but if it not working with the ubuntu version also will be more difficult know the cause of the problem...

**Comment by rilian-la-te** [comment]
Ok, I do not know for now why it is working as working. I need an Ubuntu to test.

**Comment by rilian-la-te** [comment]
It will not be ideal, Jayatana have issues, it is not a secret. So, I need an Ubuntu 18.04 with Jayatana to test. I will try it tomorrow.

**Comment by Pitometsu** [comment]
@lestcape if it available in repositories, how can I get it? I trying to install it from git, because Idea on fresh Ubuntu 18.04 have no global menu.

**Comment by lestcape** [comment]
@Pitometsu: sudo apt-get install jayatana

Here in my work i use Ubuntu 16.04.4 and GNOME Shell 3.18.5

java -version
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
![captura de pantalla de 2018-05-22 17-35-44](https://user-images.githubusercontent.com/1389572/40393885-cb6b52de-5de6-11e8-9366-f9082574b6c3.png)

In my home i have ubuntu 18.04 and see:
https://github.com/lestcape/Gnome-Global-AppMenu/issues/93

**Comment by rilian-la-te** [comment]
@lestcape are you using my jayatana or stock?

**Comment by Pitometsu** [comment]
Cleaned, installed one from apt, rebooted. It working now, but buggy a little (e.g. disappear after Activities). Also uiDesigner error appeared first time, but I closed project (not IDE), reopen it from open dialog (not from recent) - and it working now. Almost :)

**Comment by lestcape** [comment]
@Pitometsu
> It working now, but buggy a little  

Well, yes. This is why i say that the @rilian-la-te source will be better. Theoretically it fix some annoying problems.

@rilian-la-te the ubuntu source. I never use your source. Both appmenu and jayatana are from the ubuntu repositories, not directly from your source.

**Comment by rilian-la-te** [comment]
Ok. My source fixes some problems, but tested only on Arch. And some problems remain.

**Comment by lestcape** [comment]
Yes, anyway, i don't see a reason of why not work when is installed from the source.

**Comment by lestcape** [comment]
Ok, another thing to test...

**Comment by Pitometsu** [comment]
I might be busy next days, if you need some testing from me, mention me on weekend plz.
