### ISSUE TITLE
Global menu in the application does not display after restart

### ISSUE THREAD

**Issue by tiansin** [lestcape/Gnome-Global-AppMenu#85]
Manjaro 17.1.9 
GNOME 3.28.1

When I first opened VSCode, the menu was sound, but when I turned off VSCode the next time it was turned on, the global menu was displayed. Only Alt+F2 input 'r' can be restored.

**Comment by lestcape** [comment]
Thanks...
Can you provide me the source of your installation of vscode or the version at less?

Also please, be sure you have the lasted version of the extension, I'm making a lot of changes. I supposes that you use appmenu-gtk-module from @rilian-la-te AUR or git source, you are in X11 and your gnome version is 3.28.1. 

All that assumptions are ok?

**Comment by rilian-la-te** [comment]
appmenu-gtk-module is not needed for VSCode, it uses DBusMenu.

**Comment by lestcape** [comment]
That fine... I'm who not installed MS tools on linux yet, so sorry for the noise.

**Comment by rilian-la-te** [comment]
It is Electron app, so, it is a logic, not only a knowledge.

**Comment by tiansin** [comment]
Thanks for your reply, I pulled the latest submission code, this issue has been fixed. @lestcape 
[https://github.com/lestcape/Gnome-Global-AppMenu/commit/76fa08a12445d849e334192ec771accc36a0ba7f](url)
