### ISSUE TITLE
Secondary menu cannot pop up on multiple screens

### ISSUE THREAD

**Issue by tiansin** [lestcape/Gnome-Global-AppMenu#86]
Manjaro 17.1.9
GNOME 3.28.1
VSCode 1.23

When the default primary and secondary screen order, the menu pops up is normal, when I set the notebook screen as the secondary screen and the external screen is set as the primary screen, the secondary menu cannot appear.

![peek 2018-05-04 10-34](https://user-images.githubusercontent.com/4232281/39611150-0cd7cddc-4f88-11e8-80d8-dce21140181a.gif)

**Comment by lestcape** [comment]
Hi, i have not more than one monitor... I have not idea of occurs then... One thing could help, is know where is the panel and the space available in both sides to display the menu.

**Comment by lestcape** [comment]
This error was migrated to gitlab, as the development of this extension, will no longer be in github from the recently acquisition from the Microsoft company of the github website. Please to continued following it you can subscribed in this thread:
https://gitlab.com/lestcape/Gnome-Global-AppMenu/issues/86
