### ISSUE TITLE
Does not work with pycharm

### ISSUE THREAD

**Issue by jeroen7s** [lestcape/Gnome-Global-AppMenu#87]
i've tried to use it with pycharm, but it doesn't seem to work
i have:
> "-javaagent:/usr/share/java/jayatanaag.jar" set in vm.options
"linux.native.menu=true" set in pycharm options

and i have the JAyatana option enabled in the extension and installed
the menu seems to disapear in pycharm, but not appear on my top panel thingy
Global Appmenu seems to work for everything else, tho i haven't tried any other java programs that need JAyatana yet
running Ubuntu Gnome 16.04

**Comment by lestcape** [comment]
Sorry, but there are not a package available from ubuntu. I don' t know what GUI is used by pycharm. The Global menu only support Qt and Gtk toolkits.

**Comment by lestcape** [comment]
Please be sure that you have the lasted version of pycharm and the last version of gnome global menu. Pycharm use a java GUI and then it can be supported and it's supported.

![captura de pantalla de 2018-05-04 08-41-41](https://user-images.githubusercontent.com/1389572/39631152-0a410464-4f77-11e8-956c-70bff2753487.png)

**Comment by lestcape** [comment]
Apparently the menu items are reported wrong by jayatana. I think I can not do anything with it. I don' t develop jayatana or pycharm.

**Comment by rilian-la-te** [comment]
This is a PyCharm issue, I know about it (PyCharm creates JCheckBoxMenuItem especially for JAyatana), but I do not know how to workaround it (I have this issue on vala-panel-appmenu too: https://github.com/rilian-la-te/vala-panel-appmenu/issues/137

**Comment by lestcape** [comment]
It's the same for IntelliJ Idea, is for the same company:

![captura de pantalla de 2018-05-04 11-54-25](https://user-images.githubusercontent.com/1389572/39643461-777b2eba-4f9a-11e8-8b10-ee31bff53bc0.png)

**Comment by lestcape** [comment]
@jeroen7s 
1- Remove all your workaround.
2- Install the JAyatana package
3- Enable the support in the settings:

![captura de pantalla de 2018-05-04 11-58-06](https://user-images.githubusercontent.com/1389572/39643554-bcbb97a8-4f9a-11e8-9646-2e443ccea9a7.png)
