### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by sassanh** [lestcape/Gnome-Global-AppMenu#88]
Sorry for making an issue for this. I just wanted to say thanks for this great extension but didn't any other way. I installed it with no hope that it works as expected but it worked perfectly. The settings are fantastic I was like "YEAH" "YESSSS" "WOW" "EVEN THAT" when I was passing items in the settings. Now I guess I won't fix my macOS at all as with this extension Gnome has whatever I need from a user interface. (Except blur effect macOS has on its transparent elements.)
Thank you.

**Comment by lestcape** [comment]
Thanks.
