### ISSUE TITLE
VSCode drop-down menu shows empty items

### ISSUE THREAD

**Issue by tiansin** [lestcape/Gnome-Global-AppMenu#89]
Manjaro 17.1.9
GNOME 3.28.1
VSCode 1.23

I cloned the latest code again today. The VSCode menu will be displayed on the task bar, but mouse clicks will only pop up an empty menu item.

**Comment by lestcape** [comment]
Yes, i can reproduced it, so it will be fixed. thanks.

**Comment by lestcape** [comment]
I make this change:
https://github.com/lestcape/Gnome-Global-AppMenu/commit/92d846d8e8599b74da6a9ad27bf88eb6b8eec5bd

Can you confirm if is working for you?

**Comment by tiansin** [comment]
Thank you very much. It worked well.

**Comment by tiansin** [comment]
It is normal for me to use one day today, but just a few minutes ago, this problem has occurred once, only once.

**Comment by lestcape** [comment]
Yes, the problem is that i reduced the number of updates, to be more faster and also to work really better for jayantana, with use the same mechanism, but it's really different. So the problem here is decide if is more important the performance than the quality.

**Comment by tiansin** [comment]
Well, I understand, thank you.

**Comment by lestcape** [comment]
I will make a workaround of that specific case. It's, if there are not children, i will force an update. Probably this will help. I don' t used the vscode, so will be good to know if this resolved the problematic.

**Comment by lestcape** [comment]
https://github.com/lestcape/Gnome-Global-AppMenu/commit/89dde67945851365c1eefb8e5368a40fae9bbdf7

**Comment by tiansin** [comment]
Thanks, I have to test for some time to reply．

**Comment by tiansin** [comment]
After a long time of testing, this issue has been solved, thank you!
