### ISSUE TITLE
Option to hide the icon and the window title.

### ISSUE THREAD

**Issue by dimztimz** [lestcape/Gnome-Global-AppMenu#90]
This extension lays out an Icon and short window title that fades away to the left. It would be nice if these can be hidden, only the menu to be shown.

**Comment by lestcape** [comment]
@dimztimz see the settings... Right click inside the menu...

**Comment by dimztimz** [comment]
Ok thanks, i was unable to open the settings due to #81.

**Comment by lestcape** [comment]
The extension have not a way to inform the dependencies, so this issue have not a solution from my side. Write a bug to ubuntu instead. This issue is affecting more than just this extension and is not present in gnome shell.

**Comment by tiansin** [comment]
It is normal for me to use one day today, but just a few minutes ago, this problem has occurred once, only once.
