### ISSUE TITLE
environment veriable:JAVA_TOOL_OPTIONS

### ISSUE THREAD

**Issue by innun** [lestcape/Gnome-Global-AppMenu#94]
ubuntu18.04:
The extension will set an environment veriable:JAVA_TOOL_OPTIONS to my computer,how can I remove it？

**Comment by lestcape** [comment]
In the settings, do not active the jayatana support.

**Comment by innun** [comment]
@lestcape oh thanks, but i finally make it when i active the jayatana support, it was not active before.

**Comment by lestcape** [comment]
Ohhhh i see your point. Probably will be good to check if that variable exist and if jayatana support is enable and just in that case write the variable to the user enviroment otherwise not write anything, but to be honest i don't see the difference in set it to empty or not set it at all.

**Comment by innun** [comment]
Well...if set it to empty, the terminal will show "Picked up JAVA_TOOL_OPTIONS:" every time i type java/javac command.This may be a bit annoying...

**Comment by lestcape** [comment]
This error was migrated to gitlab, as the development of this extension, will no longer be in github from the recently acquisition from the Microsoft company of the github website. Please to continued following it you can subscribed in this thread:
https://gitlab.com/lestcape/Gnome-Global-AppMenu/issues/94
