### ISSUE TITLE
Gnome global application menu(hud for gnome) conflict with virtualbox 5.2

### ISSUE THREAD

**Issue by fouvy** [lestcape/Gnome-Global-AppMenu#98]
At ubuntu 18.04, gdm3, when Gnome global application menu enable, virtualbox 5.2 will start as a black screen and after a while virtualbox 5.2 will run well. After disable Gnome global application menu, virtualbox 5.2 will start quickly with no black sreen.

**Comment by lestcape** [comment]
Have you the last version of the extension and you download it from here?

And how you think that this is a fault of this extension? If you experimented a problem with an specific application, please disable the global menu for this specific application. This always will be your option.

I don't think that this is a problem that i can resolved anyway: https://forums.virtualbox.org/viewtopic.php?f=7&t=86836

**Comment by fouvy** [comment]
I got this extension on gnome official website. After checkout last version of this repo and replace old extension fold: ~/.local/share/gnome-shell/extensions/gnomeGlobalAppMenu@lestcape , the problem solved!
