### ISSUE TITLE
alt+tab to some other app makes it hang for half a minute or so

### ISSUE THREAD

**Issue by DEvil0000** [lestcape/Gnome-Global-AppMenu#99]
using alt+tab makes the app/window to which you switch hang for some time.

you can resolve the hang by clicking window overview (which is then also slow for a second) and back.
you can resolve the hang by clicking to other windows and back.
you can resolve it by waiting.

**Comment by lestcape** [comment]
I can not reproduce that problem.

**Comment by DEvil0000** [comment]
It does not happen every time (every third to tenth time maybe) and I am doing the switch fast what might play a role.
It happens mostly when I switch to the terminal window (sized bigger and with a few tabs using ssh, top 
etc.) from chrome.
if the extension (master version) is disabled i can not reproduce it.

**Comment by lestcape** [comment]
Also please, disable all other extensions that you have, especially if you have extensions to remove the windows borders. Then, test if the problem persist.

**Comment by DEvil0000** [comment]
Ubuntu 18.04
GNOME Shell 3.28.1

I am using 3 monitores.
I have basically 4 applications open: chrome(some windows, some tabs), terminal(some tabs with ssh, one with top, one plain), atom, thunderbird
I use the following extensions: Gnome global application menu, hibernate status button, multi monitors add-on, refresh wifi connections, start overlay in application view, suspend button, ubuntu appindicators, ubuntu dock.

I can reproduce it by switching with alt+tab between chrome and the terminal (what i do quite often and sometimes fast while working) - switching between atom and the terminal is also a common pattern for me. Sometimes the bug is trigerred every time i switch to the terminal, sometimes it does not happen for 10 or more times. I did not figure out a good way to reproduce it till now but face it quite often. 
While working it seams to happen more often then when i try to reproduce it. Maybe because I try to click on an not active terminal tab direcly after switching. Maybe it depends on cpu load, window refresh/redraw/repaint (e.g. top/ssh data changing terminal displayed content while switching) or some other strange/rare things.
I will try to figure out some better way of reproducing it. Sorry for the bad reproducability

**Comment by lestcape** [comment]
This error was migrated to gitlab, as the development of this extension, will no longer be in github from the recently acquisition from the Microsoft company of the github website. Please to continued following it you can subcribed in this thread:
https://gitlab.com/lestcape/Gnome-Global-AppMenu/issues/99
